### ISSUE TITLE
보스가 등장하지 않는 버그

### ISSUE THREAD

**Issue by jandy14** [hookSSi/M.I.T.-Game#5]
**버그에 대해 설명**
모든 적을 처리해하고 거리도 충분히 움직였지만 보스가 나타나지 않는 경우가 있다.

**버그 발생 원인**
적이 스크롤이 변하면서 떨어졌는지 죽지 않고 떨어지고 있는 경우가 있었다.
그로 인해 GameManager에 있는 _totalEnemyCount가 0이 되지 않는 경우가 있다.

Enemy클래스에는 이때를 대비해 y축을 확인하고 DestroySelf를 호출하지만 이를 상속한 Civil클래스에서는 오버라이딩되어 이 코드는 없어져 문제가 생긴 듯하다.

**Comment by jandy14** [comment]
왼쪽 스폰 위치가 바닥이 없는 곳일때가 있습니다.
콜라이더를 늘리거나 스크롤을 늘리는 등의 조치가 필요해 보입니다.

**Comment by hookSSi** [comment]
f318104149d0de1c3b2b05662032e0f7ff21de99 에서 해결완료
